// 협정 금지 규칙 (설정과 무관한 고정 config)
export const AGREEMENT_BAN_CONFIG = {
  banSameManager: true,
  banManagerPairs: [
    ['윤명숙', '김대열'],
    ['윤명숙', '조정'],
    ['김장섭', '송종윤'],
    ['김장섭', '조재진'],
    ['김장섭', '이재웅'],
    ['윤한봉', '이재웅'],
    ['구본진', '송종윤'],
    ['구본진', '나의상'],
    ['조재진', '안태혁'],
    ['박성균', '나의상'],
    ['박성균', '송종윤'],
    ['박성균', '안영식'],
    ['나의상', '송종윤'],
    ['나의상', '안영식'],
    ['송종윤', '안영식'],
  ],
  banPairs: [
    [{ name: '코레일테크㈜', entityType: 'company' }, { name: '보명산업개발㈜', entityType: 'company' }],
    [{ name: '코레일테크㈜', entityType: 'company' }, { name: '해성테크㈜', entityType: 'company' }],
    [{ name: '에코엠이엔씨㈜', entityType: 'company' }, { name: '에스지씨이앤씨㈜', entityType: 'company' }],
    [{ name: '태평양이앤씨(주)', entityType: 'company' }, { name: '에스지씨이앤씨㈜', entityType: 'company' }],
    [{ name: '㈜성전사', entityType: 'company' }, { name: '에스지씨이앤씨㈜', entityType: 'company' }],
    [{ name: '㈜김앤드이', entityType: 'company' }, { name: '나의상', entityType: 'manager' }],
    [{ name: '윤명숙', entityType: 'manager' }, { name: '도원이엔아이', entityType: 'company' }],
    [{ name: '김장섭', entityType: 'manager' }, { name: '㈜왕선전설', entityType: 'company' }],
    [{ name: '김장섭', entityType: 'manager' }, { name: '㈜기전사', entityType: 'company' }],
    [{ name: '김장섭', entityType: 'manager' }, { name: '㈜보원엔지니어링', entityType: 'company' }],
    [{ name: '㈜벽산전기', entityType: 'company' }, { name: '세명건설㈜', entityType: 'company' }],
    [{ name: '㈜세영이앤씨', entityType: 'company' }, { name: '성원전기', entityType: 'company' }],
    [{ name: '㈜트래콘건설', entityType: 'company' }, { name: '이화공영㈜', entityType: 'company' }],
    [{ name: '구본진', entityType: 'manager' }, { name: '대명지이씨㈜', entityType: 'company' }],
    [{ name: '구본진', entityType: 'manager' }, { name: '㈜도화엔지니어링', entityType: 'company' }],
    [{ name: '㈜남양계전', entityType: 'company' }, { name: '㈜이엘케이', entityType: 'company' }],
    [{ name: '㈜부현전기', entityType: 'company' }, { name: '㈜하나전기', entityType: 'company' }],
    [{ name: '㈜부현전기', entityType: 'company' }, { name: '㈜유리시스템즈', entityType: 'company' }],
    [{ name: '세안이엔씨㈜', entityType: 'company' }, { name: '㈜유리시스템즈', entityType: 'company' }],
    [{ name: '세안이엔씨㈜', entityType: 'company' }, { name: '㈜하나전기', entityType: 'company' }],
    [{ name: '㈜대광건영', entityType: 'company' }, { name: '김화성', entityType: 'manager' }],
    [{ name: '㈜대한종합산전', entityType: 'company' }, { name: '㈜코원건설', entityType: 'company' }],
  ],
};
