const buildTemplateUrl = (fileName) => new URL(`../../../템플릿/${fileName}`, import.meta.url).href;

export const AGREEMENT_TEMPLATE_CONFIGS_WEB = {
  'mois-under30': {
    label: '행안부 30억 미만',
    templateUrl: buildTemplateUrl('행안부_30억미만_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      ability: ['AO', 'AP', 'AQ', 'AR', 'AS'],
    },
    approvalColumn: 'B',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
    summaryColumns: { netCostBonus: 'AG' },
  },
  'mois-30to50': {
    label: '행안부 30억~50억',
    templateUrl: buildTemplateUrl('행안부_30억~50억_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      ability: ['AP', 'AQ', 'AR', 'AS', 'AT'],
    },
    approvalColumn: 'B',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
    headerCells: { baseAmount: 'D1', estimatedAmount: 'D2' },
    summaryColumns: { netCostBonus: 'AG' },
  },
  'mois-50to100': {
    label: '행안부 50억~100억',
    templateUrl: buildTemplateUrl('행안부_50억~100억_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      ability: ['AO', 'AP', 'AQ', 'AR', 'AS'],
    },
    approvalColumn: 'B',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
    headerCells: {
      estimatedAmount: 'D1',
      baseAmount: 'D2',
      bidAmount: 'F2',
      noticeTitle: 'N1',
      bidDeadline: 'O2',
      dutySummary: 'U2',
      entryAmountNote: 'AA2',
      entryAmount: 'AQ3',
    },
    summaryColumns: { netCostBonus: 'AG' },
  },
  'pps-under50': {
    label: '조달청 50억 미만',
    templateUrl: buildTemplateUrl('조달청50억미만_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      ability: ['AO', 'AP', 'AQ', 'AR', 'AS'],
    },
    headerCells: {
      estimatedAmount: 'D1',
      baseAmount: 'D2',
      bidAmount: 'F2',
      noticeTitle: 'M1',
      bidDeadline: 'P2',
      dutySummary: 'AH1',
    },
    approvalColumn: 'B',
    summaryColumns: { credibility: 'AD' },
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'lh-under50': {
    label: 'LH 50억 미만',
    templateUrl: buildTemplateUrl('LH50억미만_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    rowStep: 2,
    qualityRowOffset: 1,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      ability: ['AR', 'AS', 'AT', 'AU', 'AV'],
    },
    qualityColumns: ['I', 'J', 'K', 'L', 'M'],
    headerCells: {
      estimatedAmount: 'D1',
      baseAmount: 'D2',
      ratioBaseAmount: 'I1',
      entryAmount: 'AI1',
      noticeTitle: 'K1',
      bidDeadline: 'M2',
      dutySummary: 'Q2',
      netCostPenaltyNotice: 'AF2',
    },
    approvalColumn: 'B',
    summaryColumns: { credibility: 'AF', netCostBonus: 'AG', qualityPoints: 'AD' },
    managementBonusColumn: 'O',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'lh-50to100-et': {
    label: 'LH 50억~100억(전기,통신)',
    templateUrl: buildTemplateUrl('LH50억~100억(전기,통신)_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    rowStep: 2,
    qualityRowOffset: 1,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      ability: ['AT', 'AU', 'AV', 'AW', 'AX'],
    },
    qualityColumns: ['I', 'J', 'K', 'L', 'M'],
    headerCells: {
      estimatedAmount: 'D1',
      baseAmount: 'D2',
      ratioBaseAmount: 'I1',
      entryAmount: 'AG1',
      noticeTitle: 'K1',
      bidDeadline: 'M2',
      dutySummary: 'Q2',
      netCostPenaltyNotice: 'AD2',
    },
    approvalColumn: 'B',
    summaryColumns: { qualityPoints: 'AD', credibility: 'AF', netCostBonus: 'AG' },
    managementBonusColumn: 'O',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'lh-50to100-sobang': {
    label: 'LH 50억~100억(소방)',
    templateUrl: buildTemplateUrl('LH50억~100억(소방)_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    rowStep: 2,
    qualityRowOffset: 1,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      ability: ['AT', 'AU', 'AV', 'AW', 'AX'],
    },
    qualityColumns: ['I', 'J', 'K', 'L', 'M'],
    headerCells: {
      estimatedAmount: 'D1',
      baseAmount: 'D2',
      ratioBaseAmount: 'I1',
      entryAmount: 'AG1',
      noticeTitle: 'K1',
      bidDeadline: 'M2',
      dutySummary: 'Q2',
      netCostPenaltyNotice: 'AD2',
    },
    approvalColumn: 'B',
    summaryColumns: { qualityPoints: 'AD', credibility: 'AF', netCostBonus: 'AG' },
    managementBonusColumn: 'O',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'lh-100to300': {
    label: 'LH 100억~300억',
    templateUrl: buildTemplateUrl('LH간이종심100-300억_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    rowStep: 2,
    qualityRowOffset: 1,
    managementScoreMax: 8,
    qualityHighlightMin: 88,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
    },
    qualityColumns: ['P', 'Q', 'R', 'S', 'T'],
    headerCells: {
      estimatedAmount: 'E1',
      baseAmount: 'E2',
      ratioBaseAmount: 'H1',
      noticeTitle: 'O1',
      bidDeadline: 'P2',
      dutySummary: 'U2',
    },
    approvalColumn: 'B',
    summaryColumns: { credibility: 'AF', netCostBonus: 'AG' },
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'krail-under50': {
    label: '국가철도공단 50억 미만',
    templateUrl: buildTemplateUrl('국가철도50억미만_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      technician: ['AD', 'AE', 'AF', 'AG', 'AH'],
      ability: ['AV', 'AW', 'AX', 'AY', 'AZ'],
    },
    headerCells: {
      baseAmount: 'D2',
      amountForScore: 'I1',
      noticeTitle: 'N1',
      bidDeadline: 'P2',
      dutySummary: 'U2',
      memo: 'AD1',
    },
    approvalColumn: 'B',
    summaryColumns: { credibility: 'AK' },
    credibilityScale: 0.5 / 3,
    credibilityScaleExpr: '0.5/3',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'krail-under50-sobang': {
    label: '국가철도공단 50억 미만(소방)',
    templateUrl: buildTemplateUrl('국가철도50억미만(소방)_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      technician: ['AD', 'AE', 'AF', 'AG', 'AH'],
      ability: ['AV', 'AW', 'AX', 'AY', 'AZ'],
    },
    headerCells: {
      baseAmount: 'D2',
      amountForScore: 'I1',
      noticeTitle: 'N1',
      bidDeadline: 'P2',
      dutySummary: 'U2',
      memo: 'AD1',
    },
    approvalColumn: 'B',
    summaryColumns: { credibility: 'AK' },
    credibilityScale: 0.5 / 3,
    credibilityScaleExpr: '0.5/3',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'krail-50to100-et': {
    label: '국가철도공단 50억~100억(전기,통신)',
    templateUrl: buildTemplateUrl('국가철도50억-100억(전기)_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      technician: ['AD', 'AE', 'AF', 'AG', 'AH'],
      ability: ['AW', 'AX', 'AY', 'AZ', 'BA'],
    },
    headerCells: {
      baseAmount: 'D2',
      estimatedAmount: 'I1',
      noticeTitle: 'L1',
      bidDeadline: 'P2',
      dutySummary: 'U2',
      memo: 'AD1',
    },
    approvalColumn: 'B',
    summaryColumns: { subcontract: 'AK', credibility: 'AL' },
    credibilityScale: 0.9 / 3,
    credibilityScaleExpr: '0.9/3',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'krail-50to100-sobang': {
    label: '국가철도공단 50억~100억(소방)',
    templateUrl: buildTemplateUrl('국가철도50억-100억(소방)_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      technician: ['AD', 'AE', 'AF', 'AG', 'AH'],
      ability: ['AW', 'AX', 'AY', 'AZ', 'BA'],
    },
    headerCells: {
      baseAmount: 'D2',
      estimatedAmount: 'I1',
      noticeTitle: 'L1',
      bidDeadline: 'P2',
      dutySummary: 'U2',
      memo: 'AD1',
    },
    approvalColumn: 'B',
    summaryColumns: { subcontract: 'AK', credibility: 'AL' },
    credibilityScale: 0.9 / 3,
    credibilityScaleExpr: '0.9/3',
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
  'ex-under50': {
    label: '한국도로공사 50억 미만',
    templateUrl: buildTemplateUrl('한국도로공사50억미만_템플릿.xlsx'),
    sheetName: '양식',
    startRow: 5,
    maxRows: 68,
    slotColumns: {
      name: ['C', 'D', 'E', 'F', 'G'],
      share: ['I', 'J', 'K', 'L', 'M'],
      management: ['P', 'Q', 'R', 'S', 'T'],
      performance: ['W', 'X', 'Y', 'Z', 'AA'],
      ability: ['AO', 'AP', 'AQ', 'AR', 'AS'],
    },
    headerCells: {
      estimatedAmount: 'D1',
      baseAmount: 'D2',
      noticeTitle: 'M1',
      bidDeadline: 'P2',
      dutySummary: 'AH1',
      memo: 'W2',
    },
    approvalColumn: 'B',
    summaryColumns: { credibility: 'AD' },
    regionFill: { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFFF00' }, bgColor: { indexed: 64 } },
  },
};

export const resolveWebAgreementTemplateConfig = (templateKey) => {
  if (!templateKey) return null;
  return AGREEMENT_TEMPLATE_CONFIGS_WEB[templateKey] || null;
};
